task is ready
Aysel63/flight-booking-app pull request #9
Opened 2024-11-11 18:28 UTC by Maharram-Heydarov

2024-11-11 18:35 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/controller/BookingController.java
> +    public List<BookingDto> findBookingByPassenger(String fullName) {
1 passenger can book multiple flights. It would be better to name method 'findAllBookingsByPassenger'

2024-11-11 18:38 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/controller/FlightController.java
> +    }
finding flights should be done with `destination`, `date`, `number of people` (how many tickets to buy)

2024-11-11 18:41 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/model/dto/BookingDto.java
> +    private String lastName;
dto fields should be final, so they can be transferred without changes
(remove setters too, constructor will set final variables)

2024-11-11 18:42 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/model/dto/FlightDto.java
> +    }
no need for this

2024-11-11 18:43 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/FlightService.java
> +    List<FlightDto> findFlights(String destination);
`destination`, `date`, `number of people`

2024-11-11 18:45 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/impl/BookingServiceImpl.java
> +    public BookingServiceImpl() {
...how does this constructor inject dependencies without dependencies?
please add `BookingDao bookingDao`, `FlightDao flightDao` in constructor

2024-11-11 18:50 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/impl/BookingServiceImpl.java
> +        }
not a good approach.
we can do this and handle it in controller or console:
`flightDao.getById(flightId)
.orElseThrow(() -> new NotFoundException("couldn't be able to find flight with id " + flightId));`

2024-11-11 19:00 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/impl/BookingServiceImpl.java
> +        BookingEntity bookingEntity = new BookingEntity(0, flight.get(), firstName, lastName);
on line 31, we shouldn't set bookingId manually, especially not 0.

2024-11-11 19:01 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/impl/FlightServiceImpl.java
> +                .filter(f -> f.getDestination().equals(destination) && f.getFrom().equals(f))
f.getFrom().equals(f) ?

2024-11-11 19:03 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/service/impl/FlightServiceImpl.java
> +                ))
you can use .map between .filter and .collect above, so you won't have to repeat again

2024-11-11 19:11 UTC, Semmed-Kosayev commented on src/main/java/az/edu/turing/controller/FlightController.java
> +    private FlightService flightService = new FlightServiceImpl();
Dependency Injection on line 10, please

2024-11-11 19:11 UTC, Semmed-Kosayev requested changes
thank you for your hard work
(Entities should use AtomicLong to generate values. You can leave it to someone else if you want)

2024-11-12 06:47 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/entities/BookingEntity.java
> +    private static final AtomicLong atomicCounter = new AtomicLong(0);
what is that for?

2024-11-12 07:13 UTC, merged